[package]
name = "reflective_derive_proc_macro_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflective-derive = { path = "./reflective-derive"}