[package]
name = "surreal_db_example"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = "1.5.2"
serde = { version = "1.0.203", features = ["derive"] }
#async-std = { version = "1.12.0", features = ["attributes"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }